name: Release crate (crates.io only)
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    uses: mlm-games/ci/.github/workflows/crate-publish.yml@main
    with:
      create-release: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}